# Generated by Django 3.2.16 on 2023-04-27 10:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_group_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('following', django.db.models.expressions.F('follower')), _negated=True), name='no_self_follow'),
        ),
    ]
